import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: {
          primary:   "var(--bg-primary)",
          secondary: "var(--bg-secondary)",
          elevated:  "var(--bg-elevated)",
          code:      "var(--bg-code)",
        },
        text: {
          primary:   "var(--text-primary)",
          secondary: "var(--text-secondary)",
          muted:     "var(--text-muted)",
          disabled:  "var(--text-disabled)",
        },
        border: {
          DEFAULT: "var(--border-default)",
          subtle:  "var(--border-subtle)",
          strong:  "var(--border-strong)",
        },
        brand: {
          black: "var(--brand-black)",
          white: "var(--brand-white)",
        },
        accent: {
          blue:       "var(--accent-blue)",
          "blue-hover": "var(--accent-blue-hover)",
          "blue-muted": "var(--accent-blue-muted)",
        },
        semantic: {
          success: "var(--semantic-success)",
          error:   "var(--semantic-error)",
          warning: "var(--semantic-warning)",
          info:    "var(--semantic-info)",
        },
      },
      fontFamily: {
        sans: [
          "-apple-system",
          "BlinkMacSystemFont",
          '"SF Pro Text"',
          '"Segoe UI"',
          "Helvetica",
          "Arial",
          "sans-serif",
        ],
        serif: [
          '"EB Garamond"',
          "Georgia",
          '"Times New Roman"',
          "serif",
        ],
        cursive: [
          '"Dancing Script"',
          "cursive",
        ],
        mono: [
          "ui-monospace",
          "SFMono-Regular",
          "Menlo",
          "Monaco",
          "Consolas",
          '"Liberation Mono"',
          '"Courier New"',
          "monospace",
        ],
      },
      fontSize: {
        "2xs": ["10px", "14px"],
        xs:   ["12px", "16px"],
        sm:   ["13px", "18px"],
        base: ["14px", "20px"],
        md:   ["15px", "22px"],
        lg:   ["16px", "24px"],
        xl:   ["18px", "28px"],
        "2xl": ["22px", "30px"],
        "3xl": ["28px", "36px"],
        "4xl": ["36px", "44px"],
        "5xl": ["46px", "56px"],
        "6xl": ["58px", "68px"],
        "7xl": ["72px", "84px"],
      },
      borderRadius: {
        none: "0px",
        xs:   "2px",
        sm:   "3px",
        md:   "4px",
        lg:   "6px",
      },
      boxShadow: {
        none:   "none",
        subtle: "0 1px 2px 0 rgba(0,0,0,0.04)",
        nav:    "0 1px 0 0 var(--border-default)",
        float:  "0 2px 12px 0 rgba(0,0,0,0.06), 0 0 0 1px var(--border-default)",
      },
      spacing: {
        px: "1px",
        0.5: "2px",
        1:   "4px",
        1.5: "6px",
        2:   "8px",
        2.5: "10px",
        3:   "12px",
        3.5: "14px",
        4:   "16px",
        5:   "20px",
        6:   "24px",
        7:   "28px",
        8:   "32px",
        9:   "36px",
        10:  "40px",
        11:  "44px",
        12:  "48px",
        14:  "56px",
        16:  "64px",
        20:  "80px",
        24:  "96px",
        28:  "112px",
        32:  "128px",
        40:  "160px",
        48:  "192px",
        56:  "224px",
        64:  "256px",
      },
      maxWidth: {
        container: "1280px",
        prose:     "680px",
        "prose-lg": "780px",
      },
      transitionTimingFunction: {
        apple:    "cubic-bezier(0.16, 1, 0.3, 1)",
        standard: "cubic-bezier(0.4, 0, 0.2, 1)",
      },
      transitionDuration: {
        micro:      "80ms",
        interface:  "160ms",
        transition: "280ms",
        editorial:  "500ms",
      },
    },
  },
  plugins: [],
};

export default config;
